{% set version = "3.14.0" %}
{% set dev = "" %}
{% set dev_ = "" %}
{% set ver2 = '.'.join(version.split('.')[0:2]) %}
{% set ver2nd = ''.join(version.split('.')[0:2]) %}
{% set ver3nd = ''.join(version.split('.')[0:3]) %}
{% set build_number = 2 %}

# this makes the linter happy
{% set channel_targets = channel_targets or 'conda-forge main' %}

# Sanitize build system env. var tweak parameters
# (passed to the build scripts via script_env).
{% if freethreading is not defined %}
  {% set freethreading = "yes" %}
{% endif %}

{% set abi_tag = "cp" + ver2nd %}
# freethreading, set using conda_build_config.yaml
{% if freethreading == "yes" %}
  {% set abi_tag = abi_tag + "t" %}
{% else %}
  {% set build_number = build_number + 100 %}
{% endif %}

{% if build_type == "debug" %}
  {% set py_interp_debug = "yes" %}
  {% set debug = "_debug" %}
{% else %}
  {% set py_interp_debug = "no" %}
  {% set debug = "" %}
{% endif %}

{% if win %}
  {% set site_packages_path = "Lib/site-packages" %}
{% elif freethreading == "yes" %}
  {% set site_packages_path = "lib/python" + ver2 + "t/site-packages" %}
{% else %}
  {% set site_packages_path = "lib/python" + ver2 + "/site-packages" %}
{% endif %}

package:
  name: python
  version: {{ version }}{{ dev }}

source:
  - url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}{{ dev }}.tar.xz
    # md5 from: https://www.python.org/downloads/release/python-{{ ver3nd }}{{ dev }}/
    md5: 41389edaf9c643263cbed9b5ed307df8
    patches:
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-Do-not-download-externals.patch
      - patches/0003-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0004-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0005-Unvendor-openssl.patch
      - patches/0006-Unvendor-sqlite3.patch
      - patches/0007-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0008-Doing-d1trimfile.patch
      # https://github.com/python/cpython/pull/23523
      - patches/0009-cross-compile-darwin.patch
      - patches/0010-Fix-TZPATH-on-windows.patch
      # https://github.com/python/cpython/pull/24324
      - patches/0011-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0012-Unvendor-bzip2.patch
      - patches/0013-Unvendor-libffi.patch
      - patches/0014-Unvendor-tcltk.patch
      - patches/0015-unvendor-xz.patch
      - patches/0016-unvendor-zlib.patch  # [win]
      - patches/0017-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0018-Unvendor-expat.patch
      - patches/0019-Remove-unused-readelf.patch
      - patches/0020-Don-t-checksharedmods-if-cross-compiling.patch
      - patches/0021-Override-configure-LIBFFI.patch
      - patches/0022-Unvendor-libmpdec.patch
{% if 'conda-forge' in channel_targets %}
      - patches/0023-Brand-conda-forge.patch
{% endif %}
      - patches/0024-Do-not-define-pid_t-as-it-might-conflict-with-the-ac.patch
      - patches/0025-Unvendor-zstd.patch
      - patches/0026-Use-zlib-ng-on-unix-instead-of-zlib.patch
      - patches/0027-Patch-out-zlib.h-headers.patch

build:
  number: {{ build_number }}
  activate_in_script: true
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.pyd  # [win]
  ignore_run_exports_from:
    # C++ only installed so CXX is defined for distutils/sysconfig.
    - {{ compiler('cxx') }}  # [unix]
    # These two are just to get the headers needed for tk.h, but is unused
    - xorg-libx11            # [unix]
    - xorg-xorgproto         # [unix]
  # Disabled until verified to work correctly
  detect_binary_files_with_prefix: true
  # detect_binary_files_with_prefix: False
  # binary_has_prefix_files:
  #   - lib/libpython{{ ver2 }}.*.1.0
  #   - bin/python{{ ver2 }}  # [linux]
  #   - lib/libpython{{ ver2 }}.a  # [linux]
  #   - lib/libpython{{ ver2 }}.nolto.a  # [linux]
  #   - lib/libpython3.so  # [linux]
  #   - lib/python{{ ver2 }}/lib-dynload/_hashlib.cpython-{{ ver2nd }}-x86_64-linux-gnu.so  # [linux]
  #   - lib/libpython3.dylib  # [osx]
  # match python.org compiler standard
  skip: true  # [win and int(float(vc)) < 14]
  skip_compile_pyc:
    - '*.py'            # [build_platform != target_platform]
  string: {{ dev_ }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}{{ debug }}_{{ abi_tag }}
  python_site_packages_path: {{ site_packages_path }}
  run_exports:
    noarch:
      - python
    weak:
      - python_abi {{ ver2 }}.* *_{{ abi_tag }}
{% if py_interp_debug == "yes" %}
      - python {{ ver2 }}.* *_debug_{{ abi_tag }}
{% endif %}
  script_env:
    - PY_INTERP_DEBUG={{ py_interp_debug }}
    - PY_FREETHREADING={{ freethreading }}
    # Putting these here means they get emitted to build_env_setup.{sh,bat} meaning we can launch IDEs
    # after sourcing or calling that script without examine the contents of conda_build.{sh,bat} for
    # important env. vars.
  missing_dso_whitelist:   # [win]
    - '**/MSVCR71.dll'  # [win]
    - '**/MSVCR80.dll'  # [win]
    # I have no idea why this is not in C:\Windows\System32\downlevel
    - '**/api-ms-win-core-path-l1-1-0.dll'  # [win]
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - make  # [not win]
    - libtool  # [unix]
    - pkg-config  # [not win]
    # configure script looks for llvm-ar for lto
    - llvm-tools  # [osx]
    - ld_impl_{{ target_platform }}  # [linux]
    - binutils_impl_{{ target_platform }}  # [linux]
    - clang-19         # [not win]
    - llvm-tools-19    # [not win]
    - clang 19.*       # [win]
    - llvm-tools 19.*  # [win]
    - bzip2          # [build_platform != target_platform]
    - libsqlite      # [build_platform != target_platform]
    - liblzma-devel  # [build_platform != target_platform]
    - zlib-ng        # [build_platform != target_platform]
    - zstd           # [build_platform != target_platform]
    - openssl        # [build_platform != target_platform]
    - readline       # [not win and build_platform != target_platform]
    - tk             # [build_platform != target_platform]
    - ncurses        # [unix and build_platform != target_platform]
    - libffi         # [build_platform != target_platform]
    - libuuid        # [linux and build_platform != target_platform]
    - libxcrypt      # [linux and build_platform != target_platform]
    - expat          # [build_platform != target_platform]
  host:
    - bzip2
    - libsqlite
    - liblzma-devel
    - zlib-ng
    - zstd
    - openssl
    - readline  # [not win]
    - tk
    # These two are just to get the headers needed for tk.h, but is unused
    - xorg-libx11       # [unix]
    - xorg-xorgproto    # [unix]
    - ncurses  # [unix]
    - libffi
    - ld_impl_{{ target_platform }} >=2.36.1  # [linux]
    - libuuid  # [linux]
    - libmpdec-devel
    - expat
  run:
    - ld_impl_{{ target_platform }} >=2.36.1  # [linux]
    - tzdata
    - python_abi {{ ver2 }}.* *_{{ abi_tag }}
test:
  commands:
    - echo on  # [win]
    - python -V
    - python3 -V            # [not win]

about:
  home: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
  summary: General purpose programming language
  description: |
    Python is a widely used high-level, general-purpose, interpreted, dynamic
    programming language. Its design philosophy emphasizes code
    readability, and its syntax allows programmers to express concepts in
    fewer lines of code than would be possible in languages such as C++ or
    Java. The language provides constructs intended to enable clear programs
    on both a small and large scale.

    We provide some meta packages for convenience.
    To get a CPython flavour, use:

        conda install cpython

    To get the freethreading build (i.e. without the Global Interpreter Lock - GIL):

        conda install python-freethreading

    To get the default build (i.e. with the GIL):

        conda install python-gil

    To enable the use of the experimental JIT compiler in CPython:

        conda install python-jit

    or set the environment variable PYTHON_JIT=1. Note that the JIT support
    is available for x86_64 builds only.

  doc_url: https://www.python.org/doc/versions/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  dev_url: https://docs.python.org/devguide/

extra:
  feedstock-name: python
  recipe-maintainers:
    - chrisburr
    - isuruf
    - jakirkham
    - mbargull
    - msarahan
    - pelson
    - ocefpaf
    - scopatz
    - katietz
    - xhochy
