bot:
  abi_migration_branches:
  - '3.9'
  - '3.10'
  - '3.11'
  - '3.12'
  - '3.13'
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  store_build_artifacts: true
provider:
  linux_64: github_actions
  linux_aarch64: github_actions
  osx_64: github_actions
  osx_arm64: github_actions
  win_64: github_actions
test: native_and_emulated
